{
  "length": 500.0,
  "width": 300.0,
  "hole_diameter": 12.0,
  "corner_offset": 25.0
}